"""ajout password_hash a utilisateur

Revision ID: 01102323828e
Revises: ad05badd1c80
Create Date: 2026-09-04 10:27:53.883551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01102323828e'
down_revision: Union[str, None] = 'ad05badd1c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateur', 'password_hash')
    # ### end Alembic commands ###
