"""add reset token fields

Revision ID: 03b95dd7aaf3
Revises: 01102323828e
Create Date: 2026-09-04 14:11:47.087090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03b95dd7aaf3'
down_revision: Union[str, None] = '01102323828e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('reset_token', sa.String(length=255), nullable=True))
    op.add_column('utilisateur', sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_utilisateur_reset_token'), 'utilisateur', ['reset_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utilisateur_reset_token'), table_name='utilisateur')
    op.drop_column('utilisateur', 'reset_token_expires')
    op.drop_column('utilisateur', 'reset_token')
    # ### end Alembic commands ###
