"""modification indice reading

Revision ID: 268412b74143
Revises: faf4cb60a5bb
Create Date: 2026-09-28 15:38:50.455949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '268412b74143'
down_revision: Union[str, None] = 'faf4cb60a5bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indice_reading', sa.Column('min_value', sa.Float(), nullable=True, comment='Valeur minimale observée sur la parcelle'))
    op.add_column('indice_reading', sa.Column('max_value', sa.Float(), nullable=True, comment='Valeur maximale observée sur la parcelle'))
    op.add_column('indice_reading', sa.Column('std_value', sa.Float(), nullable=True, comment='Écart-type (hétérogénéité de la parcelle)'))
    op.add_column('indice_reading', sa.Column('median_value', sa.Float(), nullable=True, comment='Valeur médiane (robuste aux outliers)'))
    op.add_column('indice_reading', sa.Column('valid_pixels', sa.Integer(), nullable=True, comment='Nombre de pixels valides (hors nuages et hors nodata)'))
    op.add_column('indice_reading', sa.Column('cloud_pixels', sa.Integer(), nullable=True, comment='Nombre de pixels masqués par SCL (nuages/ombres/neige)'))
    op.add_column('indice_reading', sa.Column('total_pixels', sa.Integer(), nullable=True, comment='Nombre total de pixels dans la parcelle'))
    op.add_column('indice_reading', sa.Column('valid_ratio', sa.Float(), nullable=True, comment='Ratio de validité = valid_pixels / total_pixels (0 à 1)'))
    op.add_column('indice_reading', sa.Column('theoretical_min', sa.Float(), nullable=False, comment="Borne théorique minimale de l'indice (ex: -1.0 pour NDVI)"))
    op.add_column('indice_reading', sa.Column('theoretical_max', sa.Float(), nullable=False, comment="Borne théorique maximale de l'indice (ex: 1.0 pour NDVI)"))
    op.add_column('indice_reading', sa.Column('is_valid', sa.Boolean(), server_default='true', nullable=False, comment='True si toutes les valeurs respectent les bornes théoriques'))
    op.add_column('indice_reading', sa.Column('validation_error', sa.Text(), nullable=True, comment="Message d'erreur si is_valid=False"))
    op.add_column('indice_reading', sa.Column('scene_id', sa.String(length=255), nullable=True, comment='ID unique de la scène : S2B_MSIL2A_20260909T101019_...'))
    op.add_column('indice_reading', sa.Column('scene_date', sa.Date(), nullable=True, comment='Date de la scène (YYYY-MM-DD)'))
    op.add_column('indice_reading', sa.Column('cloud_cover', sa.Float(), nullable=True, comment='% de nuages global de la scène'))
    op.add_column('indice_reading', sa.Column('b2_key', sa.String(length=500), nullable=True, comment='Clé B2 du COG généré (ex: rasters/farm_X/parcel_Y/sentinel_ndvi/2026-09-09.tif)'))
    op.add_column('indice_reading', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment="Date d'insertion en base (technique)"))
    op.alter_column('indice_reading', 'indice_name',
               existing_type=sa.VARCHAR(length=50),
               comment="Nom de l'indice : NDVI, NDMI, NDWI, NDRE, EVI, SAVI, MSAVI, NBR, REDEDGE, VARI, CARBONATE, SI_SOIL, PSRI, FCOVER",
               existing_nullable=False)
    op.alter_column('indice_reading', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               comment='Moyenne des pixels valides sur la parcelle')
    op.alter_column('indice_reading', 'recorded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment='Date de la scène (datetime complet avec timezone)',
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_indice_reading_is_valid'), 'indice_reading', ['is_valid'], unique=False)
    op.create_index('ix_indice_reading_parcel_indice_date', 'indice_reading', ['parcel_id', 'indice_name', 'scene_date'], unique=False)
    op.create_index(op.f('ix_indice_reading_recorded_at'), 'indice_reading', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_indice_reading_scene_date'), 'indice_reading', ['scene_date'], unique=False)
    op.create_index(op.f('ix_indice_reading_scene_id'), 'indice_reading', ['scene_id'], unique=False)
    op.create_index('ix_indice_reading_valid', 'indice_reading', ['is_valid'], unique=False)
    op.create_unique_constraint('uq_indice_reading_parcel_indice_scene', 'indice_reading', ['parcel_id', 'indice_name', 'scene_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_indice_reading_parcel_indice_scene', 'indice_reading', type_='unique')
    op.drop_index('ix_indice_reading_valid', table_name='indice_reading')
    op.drop_index(op.f('ix_indice_reading_scene_id'), table_name='indice_reading')
    op.drop_index(op.f('ix_indice_reading_scene_date'), table_name='indice_reading')
    op.drop_index(op.f('ix_indice_reading_recorded_at'), table_name='indice_reading')
    op.drop_index('ix_indice_reading_parcel_indice_date', table_name='indice_reading')
    op.drop_index(op.f('ix_indice_reading_is_valid'), table_name='indice_reading')
    op.alter_column('indice_reading', 'recorded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment=None,
               existing_comment='Date de la scène (datetime complet avec timezone)',
               existing_server_default=sa.text('now()'))
    op.alter_column('indice_reading', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               comment=None,
               existing_comment='Moyenne des pixels valides sur la parcelle')
    op.alter_column('indice_reading', 'indice_name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Nom de l'indice : NDVI, NDMI, NDWI, NDRE, EVI, SAVI, MSAVI, NBR, REDEDGE, VARI, CARBONATE, SI_SOIL, PSRI, FCOVER",
               existing_nullable=False)
    op.drop_column('indice_reading', 'created_at')
    op.drop_column('indice_reading', 'b2_key')
    op.drop_column('indice_reading', 'cloud_cover')
    op.drop_column('indice_reading', 'scene_date')
    op.drop_column('indice_reading', 'scene_id')
    op.drop_column('indice_reading', 'validation_error')
    op.drop_column('indice_reading', 'is_valid')
    op.drop_column('indice_reading', 'theoretical_max')
    op.drop_column('indice_reading', 'theoretical_min')
    op.drop_column('indice_reading', 'valid_ratio')
    op.drop_column('indice_reading', 'total_pixels')
    op.drop_column('indice_reading', 'cloud_pixels')
    op.drop_column('indice_reading', 'valid_pixels')
    op.drop_column('indice_reading', 'median_value')
    op.drop_column('indice_reading', 'std_value')
    op.drop_column('indice_reading', 'max_value')
    op.drop_column('indice_reading', 'min_value')
    # ### end Alembic commands ###
