"""ajout lignes bbx au raster

Revision ID: 481c335a2274
Revises: 81cf75d5f27f
Create Date: 2026-09-25 17:19:04.681952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '481c335a2274'
down_revision: Union[str, None] = '81cf75d5f27f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raster', sa.Column('bbox_west', sa.Float(), nullable=True))
    op.add_column('raster', sa.Column('bbox_south', sa.Float(), nullable=True))
    op.add_column('raster', sa.Column('bbox_east', sa.Float(), nullable=True))
    op.add_column('raster', sa.Column('bbox_north', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raster', 'bbox_north')
    op.drop_column('raster', 'bbox_east')
    op.drop_column('raster', 'bbox_south')
    op.drop_column('raster', 'bbox_west')
    # ### end Alembic commands ###
