"""ajout role et password_changed_at

Revision ID: 4bf721b21d8f
Revises: d158f1b9209d
Create Date: 2026-09-07 09:59:55.990877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bf721b21d8f'
down_revision: Union[str, None] = 'd158f1b9209d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('role', sa.String(length=20), server_default='user', nullable=False))
    op.add_column('utilisateur', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_utilisateur_reset_token', table_name='utilisateur')
    op.drop_column('utilisateur', 'reset_token_expires')
    op.drop_column('utilisateur', 'reset_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('reset_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('utilisateur', sa.Column('reset_token_expires', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index('ix_utilisateur_reset_token', 'utilisateur', ['reset_token'], unique=True)
    op.drop_column('utilisateur', 'password_changed_at')
    op.drop_column('utilisateur', 'role')
    # ### end Alembic commands ###
