"""check pending

Revision ID: 4c97bfc1a3e4
Revises: c434e3c1fc7b
Create Date: 2026-09-22 16:21:30.873761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '4c97bfc1a3e4'
down_revision: Union[str, None] = 'c434e3c1fc7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('agenda_event_user_id_fkey', 'agenda_event', type_='foreignkey')
    op.create_foreign_key(None, 'agenda_event', 'utilisateur', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('farm', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('parcel', sa.Column('raster_id', sa.Integer(), nullable=True))
    op.add_column('parcel', sa.Column('spatial_reference_id', sa.Integer(), server_default='4326', nullable=False))
    op.alter_column('parcel', 'culture_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('parcel', 'area_ha',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('parcel', 'geom',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               nullable=False)
    op.alter_column('parcel', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('parcel', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_parcel_raster_id'), 'parcel', ['raster_id'], unique=False)
    op.create_index(op.f('ix_parcel_spatial_reference_id'), 'parcel', ['spatial_reference_id'], unique=False)
    op.drop_constraint('parcel_farm_id_fkey', 'parcel', type_='foreignkey')
    op.create_foreign_key(None, 'parcel', 'raster', ['raster_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'parcel', 'farm', ['farm_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_utilisateur_reset_token'), 'utilisateur', ['reset_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utilisateur_reset_token'), table_name='utilisateur')
    op.drop_constraint(None, 'parcel', type_='foreignkey')
    op.drop_constraint(None, 'parcel', type_='foreignkey')
    op.create_foreign_key('parcel_farm_id_fkey', 'parcel', 'farm', ['farm_id'], ['id'])
    op.drop_index(op.f('ix_parcel_spatial_reference_id'), table_name='parcel')
    op.drop_index(op.f('ix_parcel_raster_id'), table_name='parcel')
    op.alter_column('parcel', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('parcel', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('parcel', 'geom',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               nullable=True)
    op.alter_column('parcel', 'area_ha',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('parcel', 'culture_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('parcel', 'spatial_reference_id')
    op.drop_column('parcel', 'raster_id')
    op.alter_column('farm', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'agenda_event', type_='foreignkey')
    op.create_foreign_key('agenda_event_user_id_fkey', 'agenda_event', 'utilisateur', ['user_id'], ['id'])
    # ### end Alembic commands ###
