"""modification de raster

Revision ID: 5278acea7e0e
Revises: 481c335a2274
Create Date: 2026-09-26 14:17:36.349559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5278acea7e0e'
down_revision: Union[str, None] = '481c335a2274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm_employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('hired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.String(length=10), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'employee_id', name='uq_farm_employee')
    )
    op.create_index(op.f('ix_farm_employee_employee_id'), 'farm_employee', ['employee_id'], unique=False)
    op.create_index(op.f('ix_farm_employee_farm_id'), 'farm_employee', ['farm_id'], unique=False)
    op.create_index(op.f('ix_farm_employee_id'), 'farm_employee', ['id'], unique=False)
    op.drop_constraint('alert_parcel_id_fkey', 'alert', type_='foreignkey')
    op.create_foreign_key(None, 'alert', 'parcel', ['parcel_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('indice_reading_parcel_id_fkey', 'indice_reading', type_='foreignkey')
    op.create_foreign_key(None, 'indice_reading', 'parcel', ['parcel_id'], ['id'], ondelete='CASCADE')
    op.add_column('parcel', sa.Column('raster_status', sa.String(length=20), server_default='pending', nullable=False))
    op.drop_index('ix_parcel_spatial_reference_id', table_name='parcel')
    op.drop_column('parcel', 'spatial_reference_id')
    op.add_column('raster', sa.Column('raster_type', sa.String(length=30), nullable=True))
    op.add_column('raster', sa.Column('scene_date', sa.DateTime(), nullable=True))
    op.add_column('raster', sa.Column('cloud_cover', sa.Float(), nullable=True))
    op.alter_column('raster', 'parcel_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('raster', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_raster_raster_type'), 'raster', ['raster_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raster_raster_type'), table_name='raster')
    op.alter_column('raster', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('raster', 'parcel_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('raster', 'cloud_cover')
    op.drop_column('raster', 'scene_date')
    op.drop_column('raster', 'raster_type')
    op.add_column('parcel', sa.Column('spatial_reference_id', sa.INTEGER(), server_default=sa.text('4326'), autoincrement=False, nullable=False))
    op.create_index('ix_parcel_spatial_reference_id', 'parcel', ['spatial_reference_id'], unique=False)
    op.drop_column('parcel', 'raster_status')
    op.drop_constraint(None, 'indice_reading', type_='foreignkey')
    op.create_foreign_key('indice_reading_parcel_id_fkey', 'indice_reading', 'parcel', ['parcel_id'], ['id'])
    op.drop_constraint(None, 'alert', type_='foreignkey')
    op.create_foreign_key('alert_parcel_id_fkey', 'alert', 'parcel', ['parcel_id'], ['id'])
    op.drop_index(op.f('ix_farm_employee_id'), table_name='farm_employee')
    op.drop_index(op.f('ix_farm_employee_farm_id'), table_name='farm_employee')
    op.drop_index(op.f('ix_farm_employee_employee_id'), table_name='farm_employee')
    op.drop_table('farm_employee')
    # ### end Alembic commands ###
