"""ajout avatar_url

Revision ID: 54be0c139af1
Revises: 4bf721b21d8f
Create Date: 2026-09-09 10:04:52.882030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54be0c139af1'
down_revision: Union[str, None] = '4bf721b21d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    op.add_column('utilisateur', sa.Column('reset_token', sa.String(length=255), nullable=True))
    op.add_column('utilisateur', sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateur', 'reset_token_expires')
    op.drop_column('utilisateur', 'reset_token')
    op.drop_column('utilisateur', 'avatar_url')
    # ### end Alembic commands ###
