"""update reminder

Revision ID: 81cf75d5f27f
Revises: 4c97bfc1a3e4
Create Date: 2026-09-22 16:59:18.265215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81cf75d5f27f'
down_revision: Union[str, None] = '4c97bfc1a3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agenda_event', sa.Column('reminder', sa.String(length=20), nullable=True))
    op.add_column('agenda_event', sa.Column('reminder_custom_minutes', sa.Integer(), nullable=True))
    op.drop_column('agenda_event', 'reminder_custom_unit')
    op.drop_column('agenda_event', 'reminder_custom_value')
    op.drop_column('agenda_event', 'reminder_unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agenda_event', sa.Column('reminder_unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('agenda_event', sa.Column('reminder_custom_value', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('agenda_event', sa.Column('reminder_custom_unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('agenda_event', 'reminder_custom_minutes')
    op.drop_column('agenda_event', 'reminder')
    # ### end Alembic commands ###
