"""add reminder_sent column

Revision ID: a13bc455f332
Revises: b4bfca3ea820
Create Date: 2026-09-10 11:23:22.707382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a13bc455f332'
down_revision: Union[str, None] = 'b4bfca3ea820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agenda_event', sa.Column('reminder_sent', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agenda_event', 'reminder_sent')
    # ### end Alembic commands ###
