"""add reminder_custom_unit to agenda_event

Revision ID: a81ea58f2a52
Revises: a13bc455f332
Create Date: 2026-09-15 09:03:03.131362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a81ea58f2a52'
down_revision: Union[str, None] = 'a13bc455f332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agenda_event', sa.Column('reminder_custom_unit', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agenda_event', 'reminder_custom_unit')
    # ### end Alembic commands ###
