"""ajout google_id a utilisateur

Revision ID: ad05badd1c80
Revises: ee901e6882a9
Create Date: 2026-09-04 10:19:03.720972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad05badd1c80'
down_revision: Union[str, None] = 'ee901e6882a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_utilisateur_google_id'), 'utilisateur', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utilisateur_google_id'), table_name='utilisateur')
    op.drop_column('utilisateur', 'google_id')
    # ### end Alembic commands ###
