"""creation table agenda_event

Revision ID: b4bfca3ea820
Revises: b700edc1790b
Create Date: 2026-09-10 09:18:44.335621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4bfca3ea820'
down_revision: Union[str, None] = '54be0c139af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agenda_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='a_faire', nullable=False),
    sa.Column('reminder', sa.String(length=20), nullable=True),
    sa.Column('reminder_custom_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agenda_event_id'), 'agenda_event', ['id'], unique=False)
    op.create_index(op.f('ix_agenda_event_user_id'), 'agenda_event', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agenda_event_user_id'), table_name='agenda_event')
    op.drop_index(op.f('ix_agenda_event_id'), table_name='agenda_event')
    op.drop_table('agenda_event')
    # ### end Alembic commands ###
