"""ajout role et password_changed_at

Revision ID: d158f1b9209d
Revises: 03b95dd7aaf3
Create Date: 2026-09-07 09:54:33.591184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd158f1b9209d'
down_revision: Union[str, None] = '03b95dd7aaf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
