"""add farm coordinates

Revision ID: eb9745be9626
Revises: 94650bfd006c
Create Date: 2026-09-16 12:07:50.737305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb9745be9626'
down_revision: Union[str, None] = '94650bfd006c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farm', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('farm', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farm', 'longitude')
    op.drop_column('farm', 'latitude')
    # ### end Alembic commands ###
