"""modification percel

Revision ID: ebfc7adf54fe
Revises: 268412b74143
Create Date: 2026-10-06 15:11:47.402779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebfc7adf54fe'
down_revision: Union[str, None] = '268412b74143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_crop_id'), 'crop', ['id'], unique=False)
    op.create_index(op.f('ix_crop_diagnosis_id'), 'crop_diagnosis', ['id'], unique=False)
    op.create_index(op.f('ix_crop_observation_id'), 'crop_observation', ['id'], unique=False)
    op.create_index(op.f('ix_parcel_analysis_id'), 'parcel_analysis', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcel_analysis_id'), table_name='parcel_analysis')
    op.drop_index(op.f('ix_crop_observation_id'), table_name='crop_observation')
    op.drop_index(op.f('ix_crop_diagnosis_id'), table_name='crop_diagnosis')
    op.drop_index(op.f('ix_crop_id'), table_name='crop')
    # ### end Alembic commands ###
